export type InfoCard = { title: string; text: string };
export type ContentSection = { heading: string; intro?: string; bullets?: string[]; cards?: InfoCard[]; callout?: { title: string; text: string } };
export type PageContent = { slug: string; navLabel: string; eyebrow: string; title: string; lead: string; metaDescription: string; aside: string; sections: ContentSection[] };

export const pages: PageContent[] = [
  {
    slug: "services", navLabel: "Services", eyebrow: "Services",
    title: "Practical support from first assessment through long-term operation.",
    lead: "Start with one defined problem, understand the risks and build only what can create useful, measurable value.",
    metaDescription: "AI assessments, workflow automation, reporting, knowledge systems, GIS integration, responsible AI training and managed support in Western Colorado.",
    aside: "Not sure which service fits? Bring the process that is consuming time, creating errors or making information hard to find.",
    sections: [
      { heading: "AI and workflow assessment", intro: "A paid assessment creates a clear starting point before anyone commits to implementation.", bullets: ["Interview owners, managers and employees", "Map current workflows and information handoffs", "Identify repetitive work, exceptions and failure points", "Review data readiness and security considerations", "Rank opportunities by effort, risk and likely return", "Deliver a practical implementation roadmap"], callout: { title: "A decision tool—not a technology shopping list", text: "The assessment may recommend automation, a smaller process improvement or no build at all. The goal is a better decision." } },
      { heading: "Small automation pilots", intro: "A pilot limits scope while proving whether the idea works in the real environment.", bullets: ["One defined workflow and measurable objective", "Connections to existing tools where practical", "Controlled testing with representative information", "Employee review and role-specific training", "Written operating and support documentation", "Outcome review before any expansion"] },
      { heading: "Reporting and document automation", intro: "Turn recurring information into consistent, reviewable outputs without losing human responsibility.", cards: [{ title: "Management reporting", text: "Consolidate recurring operational and administrative information into clearer decision support." }, { title: "Document intake", text: "Classify approved forms and attachments, extract key fields and route exceptions for review." }, { title: "Communications", text: "Prepare human-reviewed customer notices, meeting summaries, follow-ups and action items." }, { title: "Regulatory preparation", text: "Organize source information and draft repeatable reporting materials for qualified review." }] },
      { heading: "Internal knowledge systems", intro: "Make approved organizational knowledge easier to find without giving everyone access to everything.", bullets: ["Searchable SOPs, policies and technical documentation", "Permission-aware internal question answering", "Institutional-knowledge capture", "Employee onboarding assistance", "Source-linked answers and review workflows", "Ongoing content ownership and update practices"] },
      { heading: "GIS and field operations automation", intro: "Connect asset and field information with the office workflows that depend on it.", bullets: ["Field-form and inspection processing", "Work-order and maintenance support", "GIS reporting and data-quality exceptions", "Asset-information workflows", "Field-to-office handoffs", "Human-reviewed summaries and notifications"] },
      { heading: "AI readiness, governance and training", intro: "Help employees use appropriate tools with clear expectations and safeguards.", bullets: ["Employee AI-use policies", "Practical data classification", "Appropriate-tool selection", "Human-review requirements", "Department-specific training", "Responsible implementation guidance"] },
      { heading: "Managed AI support", intro: "Keep useful workflows reliable after launch with a defined support plan.", bullets: ["Monitoring and maintenance", "Controlled improvements", "Employee support", "Documentation updates", "Usage and outcome reporting", "Security and access reviews"] },
    ],
  },
  {
    slug: "utilities-and-special-districts", navLabel: "Utilities", eyebrow: "Utilities & special districts",
    title: "Operationally grounded automation for organizations that cannot afford careless technology.",
    lead: "Support reporting, administration, GIS, maintenance information and institutional knowledge while qualified people retain operational authority.",
    metaDescription: "Responsible AI consulting and workflow automation for Colorado water utilities, sanitation districts, special districts and municipal departments.",
    aside: "Utility work begins with clear system boundaries, approved information sources and defined human responsibility.",
    sections: [
      { heading: "Built for the realities of a small utility", intro: "Small districts often balance aging systems, limited internal IT capacity, regulatory workload and significant knowledge carried by a few experienced employees.", bullets: ["Recurring management and board reporting", "Customer-service and billing workflows", "SOP and institutional-knowledge organization", "Maintenance and work-order information", "GIS and asset reporting", "Employee onboarding and documentation", "Approved operational-log summaries", "Security and access practices"] },
      { heading: "Read-only operational intelligence", intro: "Approved exports can support useful analysis without giving AI authority over utility operations.", cards: [{ title: "Alarm and communication trends", text: "Summarize recurring alarms, communication failures and historical patterns from approved records." }, { title: "Runtime and cycling review", text: "Prepare pump-runtime or cycling summaries for operator and maintenance review." }, { title: "Operator summaries", text: "Draft daily or weekly operational narratives with links back to source information." }, { title: "Maintenance context", text: "Connect approved logs with GIS, work-order or maintenance information in a separate reporting environment." }], callout: { title: "Your operators stay in charge", text: "AI interpretations remain advisory drafts. Qualified operators and licensed professionals retain review, judgment and decision authority." } },
      { heading: "A firm initial boundary around OT", intro: "The consultancy does not initially perform or enable autonomous infrastructure control.", bullets: ["No direct pump or valve commands", "No chemical-feed, pressure or treatment-process control", "No PLC programming or operational configuration changes", "No write-enabled AI access to OT systems", "No public AI services installed directly in a control environment", "No replacement of licensed engineering or qualified operator judgment"] },
      { heading: "A controlled information pathway", intro: "When operational information is in scope, approved data should move through an intentional and documented path.", bullets: ["Identify the approved source and responsible owner", "Export only the necessary information", "Move information into a separate reporting environment", "Apply least-privilege and read-only access", "Flag AI-generated content as a draft", "Require qualified human review before use"] },
      { heading: "Administrative and organizational resilience", intro: "Administrative workflows often provide the safest, fastest place to begin.", bullets: ["Recurring report preparation", "Meeting notes and action tracking", "Form and document intake", "Customer communication drafts", "Policy and SOP search", "Training and employee knowledge support"] },
    ],
  },
  {
    slug: "small-businesses", navLabel: "Small Businesses", eyebrow: "Small-business automation",
    title: "Fewer dropped handoffs. Less repetitive administration. Better-supported employees.",
    lead: "Practical improvements for Western Colorado businesses that have outgrown informal processes but do not need an enterprise transformation project.",
    metaDescription: "AI workflow automation for Western Colorado contractors, property managers, agricultural businesses, nonprofits and professional offices.",
    aside: "The best first project is usually visible, repetitive and easy for employees to evaluate.",
    sections: [
      { heading: "Where small teams feel the strain", intro: "When every employee wears several hats, scattered information and manual follow-up create more risk than they appear to.", bullets: ["Customer information arrives through several channels", "The same details are entered more than once", "Follow-ups depend on individual memory", "Reports require manual spreadsheet assembly", "Policies and answers are difficult to locate", "Experienced employees become workflow bottlenecks"] },
      { heading: "Customer intake and follow-up", intro: "Create a clearer path from a new inquiry to the next responsible person.", cards: [{ title: "Intake", text: "Standardize information from forms, email or calls without complicating the customer experience." }, { title: "Routing", text: "Send the right details to the right person and surface missing information before work stalls." }, { title: "Follow-up", text: "Prepare reminders, status updates and draft communications for employee review." }, { title: "Visibility", text: "Give managers a clearer view of open requests, aging items and recurring exceptions." }] },
      { heading: "Administrative operations", intro: "Connect familiar tools instead of replacing them unnecessarily.", bullets: ["Document routing and file naming", "Recurring internal reports", "Scheduling and task follow-up", "Email and communication workflows", "Spreadsheet and database connections", "Shared-drive and knowledge organization"] },
      { heading: "Organizations this can fit", intro: "The approach is designed for local organizations with practical work and limited capacity for drawn-out consulting projects.", bullets: ["Contractors and skilled trades", "Engineering, surveying and GIS firms", "Property-management businesses", "Agricultural businesses", "Professional and administrative offices", "Nonprofits and membership organizations"] },
      { heading: "Employee-supportive implementation", intro: "The people doing the work should help shape the workflow and evaluate whether it actually helps.", callout: { title: "Automate avoidable workload—not accountability", text: "The aim is to remove repetitive steps, make handoffs clearer and give employees better information while preserving human judgment and customer relationships." } },
    ],
  },
  {
    slug: "gis-and-field-operations", navLabel: "GIS & Field Operations", eyebrow: "GIS & field operations",
    title: "Connect what happens in the field with what the office needs to know.",
    lead: "Improve field-form processing, inspection workflows, asset reporting and data-quality review without separating GIS from the people who use it.",
    metaDescription: "GIS workflow automation, field data processing, inspections, work-order support and asset information integration in Western Colorado.",
    aside: "GIS is most valuable when asset information, field observations and business workflows reinforce one another.",
    sections: [
      { heading: "Field-to-office workflows", intro: "Reduce the delay and rework between collecting information and using it.", bullets: ["Process approved mobile forms and attachments", "Route incomplete or unusual records for review", "Prepare field-activity summaries", "Connect inspection results with responsible staff", "Standardize recurring notifications", "Document each handoff and exception path"] },
      { heading: "Asset-information workflows", intro: "Bring spatial and business information together carefully, with ownership and source systems clearly defined.", cards: [{ title: "GIS reporting", text: "Turn asset and location information into recurring, audience-appropriate summaries." }, { title: "Data quality", text: "Identify missing attributes, suspicious values, duplicates and records that need human review." }, { title: "Work-order support", text: "Connect approved asset identifiers and field context with maintenance or service workflows." }, { title: "Document connections", text: "Improve the path between GIS features and relevant photos, forms, as-builts or technical records." }] },
      { heading: "Practical integration", intro: "GIS does not need to become the system of record for every detail. Good integration respects where information belongs.", bullets: ["Define authoritative systems and record ownership", "Use stable identifiers where possible", "Limit write access and automate conservatively", "Log changes and exceptions", "Preserve a human correction path", "Document dependencies and recovery steps"] },
      { heading: "Human-reviewed outputs", intro: "Automated checks and summaries are most useful when employees can understand what happened and correct it.", callout: { title: "Exceptions should become easier to see—not easier to hide", text: "The workflow should show source records, reasons for flags and the person responsible for review." } },
    ],
  },
  {
    slug: "responsible-ai-and-security", navLabel: "Responsible AI & Security", eyebrow: "Responsible AI & security",
    title: "Adopt useful AI without giving up clarity, ownership or human judgment.",
    lead: "Security is not a paragraph added after the build. It shapes which information is used, who can access it and how outputs are reviewed.",
    metaDescription: "Responsible AI governance, employee policies, secure adoption, least-privilege integration and human-review practices for Western Colorado organizations.",
    aside: "No system is risk-free and AI output is not guaranteed to be correct. Responsible design makes limitations visible and manageable.",
    sections: [
      { heading: "Core implementation commitments", intro: "Each workflow should have understandable safeguards proportionate to the information and decision involved.", bullets: ["Least-privilege access", "Read-only integrations whenever practical", "Client-owned accounts and credentials", "No unnecessary information collection", "Human review for consequential outputs", "Documented workflows, limitations and handoff", "Clear client ownership of data", "Transparent third-party services and costs"] },
      { heading: "Information and model use", intro: "AI tools differ in how they retain, process and use information. Tool selection should match the sensitivity and purpose of the work.", bullets: ["Classify information before choosing a tool", "Avoid sending confidential data to unapproved services", "Do not train public models on client information without authorization", "Limit retained information to what the workflow needs", "Use client-owned organizational accounts where available", "Review vendor terms and administrative controls"] },
      { heading: "Human review and accountability", intro: "Automation can prepare, organize and flag information. Responsibility must remain clear.", cards: [{ title: "Drafts stay drafts", text: "AI-generated summaries, communications and interpretations are labeled for review." }, { title: "Sources stay visible", text: "Where practical, outputs link back to the records or documents that support them." }, { title: "Exceptions have owners", text: "The workflow identifies who reviews unusual, incomplete or consequential items." }, { title: "Decisions remain human", text: "No autonomous safety-critical decisions or unsupported professional determinations." }] },
      { heading: "IT reporting and OT control stay separate", intro: "Operational information can support analysis without creating a control path.", callout: { title: "A deliberate separation", text: "Approved exports move into a separate reporting or staging environment. AI services do not receive write-enabled access to SCADA, PLCs or operational controls." } },
      { heading: "Governance and employee training", intro: "Policies work best when they are understandable, relevant to real roles and supported by practical examples.", bullets: ["Employee AI-use policy development", "Data classification guidance", "Approved-tool and prohibited-use definitions", "Human-review expectations", "Department-specific training", "Incident and correction pathways"] },
    ],
  },
  {
    slug: "how-engagements-work", navLabel: "How Engagements Work", eyebrow: "How engagements work",
    title: "A measured path from operational problem to useful system.",
    lead: "Begin with a clear question, test the idea in a controlled scope and expand only after employees and results support it.",
    metaDescription: "How AI consulting engagements work: introductory conversation, paid assessment, roadmap, controlled pilot, measured review and managed support.",
    aside: "Most work is packaged around defined deliverables and milestones so scope and cost are understood before implementation.",
    sections: [
      { heading: "1. Short introductory conversation", intro: "Discuss the organization, the frustrating workflow and the people affected. This is a fit check—not a full technical assessment.", bullets: ["Clarify the operational problem", "Identify likely stakeholders", "Discuss timing and broad constraints", "Determine whether a paid assessment is appropriate"] },
      { heading: "2. Paid workflow or AI-readiness assessment", intro: "Observe the actual work, information and systems involved before proposing a solution.", bullets: ["Employee and manager interviews", "Current-state workflow map", "Information and system inventory", "Risk and data-readiness review", "Opportunity ranking"] },
      { heading: "3. Prioritized roadmap", intro: "Receive a practical set of options organized by expected value, complexity, risk and dependency.", callout: { title: "An assessment does not obligate a build", text: "The roadmap belongs to the client and can support an informed decision about whether, when and how to proceed." } },
      { heading: "4. Controlled pilot", intro: "Implement one defined workflow with agreed success measures, access boundaries and human review.", bullets: ["Written scope and deliverables", "Client responsibilities and dependencies", "Testing plan", "Documentation and training", "Fallback and correction process"] },
      { heading: "5. Review measured results", intro: "Compare the pilot with the original process using time, accuracy, usability, information quality, operational impact and ongoing cost." },
      { heading: "6. Expand only if justified", intro: "If the pilot proves useful, broaden it carefully or apply the pattern to another workflow." },
      { heading: "7. Optional managed support", intro: "Choose a defined support plan for monitoring, controlled improvements, employee assistance, documentation and access reviews." },
    ],
  },
  {
    slug: "about", navLabel: "About", eyebrow: "About",
    title: "A regional technology partner for the work between people, systems and operations.",
    lead: "The consultancy combines hands-on utility, IT, GIS, data and administrative experience with a practical approach to responsible automation.",
    metaDescription: "About Randall Automation Works and Chris Randall's hands-on approach to utility technology, GIS, reporting, systems integration and employee-centered automation.",
    aside: "Specific employers, internal systems, client information and proprietary work are not displayed without written permission.",
    sections: [
      { heading: "Experience grounded in real operations", intro: "Founder Chris Randall brings hands-on experience modernizing technology, GIS, reporting and administrative workflows for a Colorado water utility.", bullets: ["Water-utility operations and administration", "Information technology and network infrastructure", "GIS and asset information", "SQL databases and reporting", "Business-system integrations", "Billing and administrative systems", "Field operations and mobile data collection", "Cybersecurity, access control and documentation"] },
      { heading: "Why that background matters", intro: "Good automation depends on more than software. It requires understanding the employee who receives the exception, the manager who relies on the report and the consequences when a handoff fails.", callout: { title: "Translation is part of the work", text: "Technical systems should be explained in language that helps owners, operators, office staff and field employees make sound decisions together." } },
      { heading: "A practical consulting philosophy", intro: "The company is built around long-term usefulness rather than novelty.", bullets: ["Begin with a real operational problem", "Respect employees and institutional knowledge", "Connect existing systems before replacing them", "Use security boundaries appropriate to the work", "Measure results before expanding", "Document the system so the client can understand it"] },
      { heading: "Western Colorado focus", intro: "The primary service area includes Montrose, Grand Junction, Delta, Ouray, Ridgway, Gunnison, Crested Butte, Telluride, Glenwood Springs, Carbondale, Rifle, Durango, Cortez and surrounding rural communities." },
    ],
  },
  {
    slug: "frequently-asked-questions", navLabel: "Frequently Asked Questions", eyebrow: "Frequently asked questions",
    title: "Straight answers about scope, security, cost and what AI can actually do.",
    lead: "A useful engagement starts with realistic expectations and clearly understood responsibility.",
    metaDescription: "Frequently asked questions about AI consulting, workflow assessments, security, pricing, utility boundaries and managed support.",
    aside: "Have a question that is not covered here? Ask it directly during an initial conversation.",
    sections: [
      { heading: "Do we need to know what should be automated?", intro: "No. A workflow assessment is designed to identify and rank opportunities with employees and managers." },
      { heading: "Do we need to replace our current software?", intro: "Usually not. The first question is whether existing spreadsheets, databases, shared drives and applications can be connected or used more consistently." },
      { heading: "Is our organization too small?", intro: "Organizations with roughly 2–100 employees often benefit because repetitive work and knowledge bottlenecks affect a larger share of the team." },
      { heading: "How is work priced?", intro: "Most assessments and implementations are scoped as defined fixed-price or milestone-based packages. Hourly rates can apply to advisory work and out-of-scope support. Ongoing services may use a monthly support package. Third-party software and AI usage are separate and disclosed." },
      { heading: "Will AI output always be correct?", intro: "No. AI can misunderstand information or generate incorrect content. Workflows use source links, review steps, limits and qualified human judgment appropriate to the risk." },
      { heading: "Does AI train on our data?", intro: "Client information is not used to train public models without authorization. Specific retention and training terms depend on the selected service and account configuration and are reviewed before use." },
      { heading: "Can this connect to SCADA?", intro: "Only approved read-only exports or separated reporting pathways may be considered initially. The consultancy does not perform autonomous control, write-enabled AI access, PLC programming or safety-critical operational decisions." },
      { heading: "What happens after a pilot?", intro: "The client reviews measured results and decides whether to stop, adjust, expand or place the workflow under a defined managed-support plan." },
      { heading: "Who owns the resulting work?", intro: "Client ownership, licenses, reusable components and third-party services are identified in the written agreement. Client data remains client-owned." },
    ],
  },
  {
    slug: "contact", navLabel: "Contact", eyebrow: "Contact",
    title: "Bring one frustrating process. Let’s find out whether it is worth improving.",
    lead: "An initial conversation is a practical fit check—no oversized transformation pitch and no need to have the solution figured out first.",
    metaDescription: "Contact Randall Automation Works to discuss a workflow assessment, automation pilot, GIS integration or responsible AI project.",
    aside: "Please do not send passwords, protected records, confidential customer data or sensitive operational information through the contact form.", sections: [],
  },
  {
    slug: "privacy", navLabel: "Privacy Policy", eyebrow: "Privacy policy",
    title: "Privacy practices should be understandable.",
    lead: "This policy explains the information the website may collect and how it is intended to be handled. It will be reviewed before public launch and updated when final service providers are selected.",
    metaDescription: "Website privacy policy for Randall Automation Works.",
    aside: "Effective date: public-launch date. This private-stage policy is prepared for final legal and service-provider review.",
    sections: [
      { heading: "Information you provide", intro: "The site may collect information submitted through a contact form, including your name, organization, email, phone, service interest, location and message." },
      { heading: "How information is used", intro: "Submitted information is used to respond to inquiries, evaluate service fit, maintain business records and improve the website. It is not sold." },
      { heading: "Sensitive information", intro: "Do not submit passwords, authentication codes, protected health information, payment-card information, confidential customer records or sensitive operational and infrastructure data." },
      { heading: "Service providers", intro: "Hosting, form delivery, scheduling, analytics and spam-protection services may process limited information. Final providers will be identified before public launch." },
      { heading: "Cookies and analytics", intro: "Optional privacy-conscious analytics may be enabled later. Material analytics or cookie use will be disclosed and controls provided where required." },
      { heading: "Retention and security", intro: "Information is retained only as long as reasonably needed. Reasonable safeguards are used, but no website or transmission method can guarantee absolute security." },
      { heading: "Your choices", intro: "You may request access to, correction of or deletion of personal information, subject to legitimate recordkeeping and legal requirements. Final contact details will be added before public launch." },
    ],
  },
  {
    slug: "terms", navLabel: "Terms & Disclaimer", eyebrow: "Terms & professional disclaimer",
    title: "Clear boundaries support better professional work.",
    lead: "These website terms describe general informational use and do not replace the written agreement for a consulting engagement.",
    metaDescription: "Website terms and professional disclaimer for Randall Automation Works.",
    aside: "These draft terms require final legal review and entity details before public launch.",
    sections: [
      { heading: "General information", intro: "Website content is provided for general informational purposes and may change. It is not a substitute for advice based on a complete review of a specific situation." },
      { heading: "No professional substitution", intro: "The consultancy does not replace licensed engineering, legal, accounting, cybersecurity, regulatory or qualified operator judgment." },
      { heading: "AI limitations", intro: "AI-generated content can be incomplete, biased or incorrect. Consequential outputs require appropriate human review." },
      { heading: "Operational systems", intro: "Website content does not authorize autonomous control, write-enabled access to operational technology, safety-critical decisions, PLC changes or substitution for qualified infrastructure personnel." },
      { heading: "No engagement through website use", intro: "Viewing the site or sending an inquiry does not create a client relationship. An engagement begins only through a mutually executed written agreement." },
      { heading: "Third-party services", intro: "References to third-party tools do not constitute a warranty or endorsement. Availability, features, pricing and terms are controlled by their providers." },
      { heading: "Intellectual property", intro: "Website text, design and original materials are protected by applicable law. Client deliverable ownership is governed by the written consulting agreement." },
      { heading: "Final legal details", intro: "The governing-law provision, legal entity name, business contact information and final limitation language will be completed before public launch." },
    ],
  },
  {
    slug: "insights", navLabel: "Insights", eyebrow: "Insights & resources",
    title: "Practical guidance for organizations considering AI and automation.",
    lead: "This section will publish only useful, experience-grounded material—not filler written to manufacture search traffic.",
    metaDescription: "Practical AI automation, utility technology, GIS workflow and responsible adoption resources for Western Colorado organizations.",
    aside: "Initial resources will be developed from recurring client questions and real operational decision points.",
    sections: [
      { heading: "Planned resource themes", intro: "The first resources will help managers make sound early decisions before choosing a tool or vendor.", cards: [{ title: "Workflow assessment guide", text: "How to identify a useful first automation project and avoid starting with the wrong problem." }, { title: "Responsible AI checklist", text: "Questions small organizations should answer about data, access, review and ownership." }, { title: "Read-only utility intelligence", text: "A plain-language guide to separating operational reporting from OT control." }, { title: "GIS field-to-office handoffs", text: "Common points where field data loses value—and practical ways to improve them." }] },
      { heading: "No thin city pages", intro: "Regional search visibility will be built through useful topic coverage and accurate service-area language rather than duplicated location pages or claims of offices that do not exist." },
    ],
  },
];

export const pageBySlug = Object.fromEntries(pages.map((page) => [page.slug, page])) as Record<string, PageContent>;
